version: '3.8'
# docker build -t fabdiangelo/testapp:latest .
# docker push fabdiangelo/testapp:latest
services:
  app:
    build: .
    image: fabdiangelo/testapp:latest
    ports:
      - "8080:8080"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - MP_PUBLIC_KEY=${MP_PUBLIC_KEY}
      - MP_ACCESS_TOKEN=${MP_ACCESS_TOKEN}